### PR TITLE
null_safety

### LINKED ISSUE #54: Null Safety Migration
Dart Null Safety is in beta and packages should start to be migrated.
[Migration guide](https://dart.dev/null-safety/migration-guide)

### PR DESCRIPTION
**Pull request by vance-liu**
fix #54, need test.

### CODE REVIEW

**Comment by zhangruiyu** [comment]
@ReinBentdal

**Review by ReinBentdal — CHANGES_REQUESTED** [review]
Could you change the url for each package in pubspec.lock to be darling.org instead of flutter-io.cn?

**Comment by vance-liu** [comment]
Changed. I tested it in my project and everything is normal. I think you'd better test it again to make sure it can be used normally. THX.

**Comment by zhangruiyu** [comment]
@ReinBentdal

**Comment by esDotDev** [comment]
Any chance this could be landed soon?

**Comment by ArneSaknussemm89** [comment]
Anything anyone can do to help this along? Wanting to update a couple apps to full nullsafety and this is the only outlier. And I *really* love using this package.

**Comment by ReinBentdal** [comment]
well, I unfortunately doesn't have the time at the moment to go through the entire package and verify the changes made. I see two possibilities to get it out fast. Either I can trust the code and push it out, or have someone else test and verify the changes.

**Comment by esDotDev** [comment]
I did a quick review and it does look pretty safe. Basically every single property was nullable already, so it's just a pass declaring everything as explicitly nullable and passing them unchanged to the flutter widgets. 

Is there any sort of test suite you use internally?

**Comment by zhangruiyu** [comment]
I have been trying to use it for nearly half a month and have not found any problems so far

**Comment by zhangruiyu** [comment]
@ReinBentdal

**Comment by ReinBentdal** [comment]
@esDotDev i don't use any specific test suite. Since there have been some users of this, and since most of the properties anyways is nullable, I will accept the pull request and push a new version

**Pull request merged**
