### PR TITLE
Decoupling facilities

### PR DESCRIPTION
**Pull request by moraispgsi**
These facilities help with decoupling styles while retaining the hot reload functionality.
```
class Styles {
  static TextWrapper get myBeautifulLabel =>
      (Text text) => text.fontSize(14).textColor(Colors.lightBlue);
}
...
Text('Lorem Ipsum').wrap(Styles.myBeautifulLabel)
...
```

Also, the context can also be provided with wrapWithContext for media queries amongst other things.

### CODE REVIEW

**Comment by ReinBentdal** [comment]
Im not really sure why this could be useful.
Why would you use this instead of for example:
```dart
Widget card({Widget child}) => Styled.widget(child: child)
  .alignment(Alignment.center)
  .backgroundColor(Colors.grey)
  .constraints(width: 100, height: 100)
  .alignment(Alignment.center);

 Widget build(BuildContext context) => card(child: Icon(Icons.ac_unit))
```
This will also update on hotreload.
How is the added complexity benefitial when we already have something very similar?

**Comment by moraispgsi** [comment]
Have you tried pulling the style out of the original class?

**Comment by ReinBentdal** [comment]
yes, this would work the exact same way
```dart
class Style {
  static Widget card({Widget child}) => Styled.widget(child: child)
    .alignment(Alignment.center)
    .backgroundColor(Colors.yellow)
    .constraints(width: 100, height: 100)
    .alignment(Alignment.center);
}

...
Widget build(BuildContext context) => Style.card(child: Icon(Icons.ac_unit))
...
```

**Comment by moraispgsi** [comment]
Hmm, I tried something similar to this and after I changed the properties the change would not be present after hot reloading, it would only work after I used the get keyword. I am using the latest version of the beta branch of flutter with dart 2.7.

**Comment by moraispgsi** [comment]
Not sure if it is important, have you tried using the styles within a stateful widget state?

**Comment by ReinBentdal** [comment]
Shure it was the exact same? final variables will not change. And yes it works with stateful widgets

**Comment by moraispgsi** [comment]
I am not sure we are doing the same thing. Regardless, if you don't find it useful that is ok. I thought you had the same problem as me after our conversation on the issue https://github.com/ReinBentdal/styled_widget/issues/15. Let's close this one, I will use my own fork for now.

**Comment by ReinBentdal** [comment]
Yes we were talking about the same issue. `final` variables does not work with hot reload. So if we want hot reload, the simplest solution is just to not have the variable defined as final.

**Comment by moraispgsi** [comment]
After upgrading it seems to work with your version.

**Pull request closed without merging**
